import {
  CATEGORY_CAPTAIN_MARVEL,
  CATEGORY_DOCTOR_STRANGE,
  CATEGORY_AVENGERS_INFINITY_WAR,
} from "utils";

export type CategoryType =
  | typeof CATEGORY_CAPTAIN_MARVEL
  | typeof CATEGORY_DOCTOR_STRANGE
  | typeof CATEGORY_AVENGERS_INFINITY_WAR;
